steps:
# TEST
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '-race', '-coverpkg=./...', '-coverprofile=coverage.txt', './...']

- name: 'gcr.io/cloud-builders/go'
  command: |
    bash <(curl -s https://codecov.io/bash)
  env:
    - CODECOV_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxx

# BUILD
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/finport:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/finport:latest", "-f", "Dockerfile", "."]


images:
- 'gcr.io/$PROJECT_ID/finport:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/finport:latest'
