steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/finport:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/finport:latest", "-f", "Dockerfile", "."]
images:
- 'gcr.io/$PROJECT_ID/mercari-api:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/mercari-api:latest'
